name: cheap_with_dif_v2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python==3.10
  - pip
  - gxx_linux-64>=9,<=12
  - ninja
  - cuda=12.1.0
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - libxcrypt
  - bioconda::tmalign
  - pip:
    - -r requirements.txt
