root_dir: /data/lux70/data/plaid
data_dir: /data/lux70/data
log_dir: /homefs/home/lux70/storage/plaid/logs
project_dir: /homefs/home/lux70/code/plaid

checkpoint_dir: ${paths.root_dir}/checkpoints
artifacts_dir: ${paths.root_dir}/artifacts
entity: lu-amy-al1